### ISSUE TITLE
The file does not exist

### ISSUE THREAD

**Issue by eldarkk** [ke112/fixios18#3]
*******r@Macbooks-MacBook-Pro *********-app % sh fixios18_en.sh
The file /Users/*********/Documents/ios/.symlinks/plugins/flutter_inappwebview_ios/ios/Classes/InAppWebView/InAppWebView.swift does not exist.
The file /Users/***********/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview_ios-*/ios/Classes/InAppWebView/InAppWebView.swift does not exist.

**Comment by ke112** [comment]
Is your question still there?     

Please try running the latest sh fixios18_en.sh, because I am in China, the mirror inconsistency caused your error
